description: Let's hack

header:
  links:
    - url: http://thestaticturtle.fr.home.tugler.fr/
      name: Portfolio
    - url: http://blog.thestaticturtle.fr.home.tugler.fr/
      name: Blog

plantuml_picoserver: http://127.0.0.1:8080/render

webMaster: 
  email: samuel@thestaticturtle.fr
  name: Samuel

managingEditor: 
  email: samuel@thestaticturtle.fr
  name: Samuel

rss:
  image: img/logo_white.png
  ttl: 60

pagination:
  articleCount: 9