#########################  Website  ###########################
baseURL: 'https://blog.staging.thestaticturtle.fr/'
refLinksNotFoundURL: "/404.html"

title: TheStaticTurtle (Staging)
copyright: Copyright 2023 - TheStaticTurtle (Currently in staging mode)
