description: Let's hack (Staging)

header:
  links:
    - url: https://website.staging.thestaticturtle.fr/
      name: Portfolio (Staging)
    - url: https://blog.staging.thestaticturtle.fr/
      name: Blog (Staging)