#########################  Website  ###########################
baseURL: 'https://blog.thestaticturtle.fr/'
refLinksNotFoundURL: "/404.html"

log: true
verbose: true
timeout: 300000 # Large timeout for the SSR of embed

enableGitInfo: true

defaultExtension: "html"
defaultLayout: "post"

##########################  Blog  #############################

theme: turtle
title: TheStaticTurtle
copyright: Copyright 2023 - TheStaticTurtle

languageCode: en-us

timeZone: "Europe/Paris"

ignoreErrors: 
  - "error-remote-getjson"

#########################  Render  ###########################

markup:
  highlight:
    guessSyntax: false
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: manni
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      xhtml: false
      unsafe: true

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  publishDate:
    - publishDate
    - date
  expiryDate:
    - expiryDate
  lastmod:
    - :git
    - lastmod
    - :fileModTime
    - date
    - publishDate

security:
  enableInlineShortcodes: true
  http:
    methods:
    - (?i)GET
    urls:
    - .*

imaging:
  exif:
    disableDate: true
    disableLatLong: true

#########################  Content  ###########################

taxonomies:
  author: authors
  tag: tags

permalinks:
  posts: '/:slug/'

section:
  - "RSS"
  - "SITEMAP"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "SITEMAP"
  page:
    - "HTML"
  section:
    - "HTML"
    - "SITEMAP"
  taxonomy:
    - "HTML"
  term:
    - "HTML"

params:
  description: Let's hack
  header:
    links:
      - url: https://thestaticturtle.fr
        name: Home
      - url: https://blog.thestaticturtle.fr/
        name: Blog
  webMaster: 
    email: samuel@thestaticturtle.fr
    name: Samuel
  managingEditor: 
    email: samuel@thestaticturtle.fr
    name: Samuel
  rss:
    image: /img/logo_white.png
    ttl: 60
