baseURL: 'http://example.org/'
languageCode: en-us
title: TheStaticTurtle
copyright: Copyright 2023 - TheStaticTurtle
theme: turtle

ignoreErrors: 
  - "error-remote-getjson"

enableGitInfo: true

permalinks:
  posts: '/:slug/'

taxonomies:
  author: authors
  tag: tags

markup:
  highlight:
    guessSyntax: false
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: manni
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      xhtml: false
      unsafe: true