baseURL: 'http://example.org/'
languageCode: en-us
title: TheStaticTurtle
copyright: Copyright 2023 - TheStaticTurtle
theme: turtle

params:
  description: Let's hack
  rss:
    image: /favicon.png
    ttl: 60
    managingEditor: 
        email: samuel@thestaticturtle.fr
        name: Samuel
    webMaster: 
        email: samuel@thestaticturtle.fr
        name: Samuel


ignoreErrors: 
  - "error-remote-getjson"

enableGitInfo: true

permalinks:
  posts: '/:slug/'


outputs:
  section:
    - "HTML"
    - "SITEMAP"
  page:
    - "HTML"
  taxonomy:
    - "HTML"
  taxonomyTerm:
    - "HTML"


taxonomies:
  author: authors
  tag: tags

markup:
  highlight:
    guessSyntax: false
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: manni
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      xhtml: false
      unsafe: true